### ISSUE TITLE
Let dispatchers assign rides in advance

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1115] opened 2018-11-06 17:57 UTC
Another one per Dan from chat.

In the case of California 25 today they have 1 wheelchair accessible vehicle, so for that one ideally they could have assigned multiple rides to that driver. 

Not sure if that covers everything he had in mind

**Comment by dryan** [comment] 2018-11-06 17:58
this scenario for sure, but just generally allowing dispatchers to pre-assign rides so everyone has their first ride known the night before.

**Comment by john** [comment] 2018-11-06 19:45
Dupe of #875, referenced this one over there so closing.

**Closed by john** 2018-11-06 19:45 UTC
