### ISSUE TITLE
Double names in Dispatcher 'Driver' Tab

### ISSUE THREAD

**Issue by smarbin** [john/drive.vote#1062] opened 2018-10-27 06:13 UTC
Most, but not all drivers are duplicates in this view. The first and last appear to be unique. 
This comes from the page: https://staging.drive.vote/dispatch/orlando/drivers

![download](https://user-images.githubusercontent.com/20249846/47600319-5e84df00-d974-11e8-8c56-8e1b0d649989.png)

**Comment by john** [comment] 2018-10-27 16:28
I think it's likely that there are actual double entries in the DB, so may be more likely sloppy data in staging than a bug--we have a file called 'seeds' that can be used to populate your local env with test data, looks like it was run multiple times on staging.

I'll check the DB directly right now, @smarbin we can sync before your next training (but not the one in 20 minutes, don't want to surprise you) about cleaning the staging data so it's easier to use and understand.

**Comment by john** [comment] 2018-10-28 05:50
Spent some time mucking in the DB, confirmed that the data is hot mess from all the banging on it we've done. In particular it looks like someone, probably me, re-ran the import of seed data into at some time, resulting in some duplicates.

I'm going to close this, because I don't think it's a code bug. But we can wipe staging if you want and set it up with new data--though maybe that's not necessary since you created the new RZs, @smarbin. Let me know.

**Closed by john** 2018-10-28 05:50 UTC
Labels: bug

**Comment by smarbin** [comment] 2018-10-29 17:17
Ok sounds like it's not necessary, thanks for checking it out!
